### ISSUE TITLE
Crash when removing layer

### ISSUE THREAD

**Issue by davidseek** [RayJiang16/XYColor#2]
I have a tableViewCell and I'm using: 

```
view.layer.sublayers?.forEach { layer in
   layer.removeFromSuperlayer()
}
```

... to prepare the cell for reuse.
That causes a crash:

Highest Thread Level: 

<img width="970" alt="Screen Shot 2020-03-02 at 6 10 35 PM" src="https://user-images.githubusercontent.com/17073950/75736078-1fc21000-5cb1-11ea-9a77-2e7a7dd85a63.png">

Below: 

<img width="984" alt="Screen Shot 2020-03-02 at 6 10 57 PM" src="https://user-images.githubusercontent.com/17073950/75736118-3bc5b180-5cb1-11ea-9c6f-4db29e751ed3.png">

Calling Side: `setLayerBorderColor`

Without deeper dive into your code,
I assume that `setLayerBorderColor` tries to access an object in memory
that I'm removing through `removeFromSuperlayer`.

I'm gonna investigate for a solution myself
as I don't know how fast you'll be able to fix it.

Possible relations:
https://stackoverflow.com/questions/16569840/using-objc-setassociatedobject-with-weak-references

**Comment by RayJiang16** [comment]
Could you show me more detail about what do you do in TableViewCell?

**Comment by davidseek** [comment]
Created an example: https://github.com/davidseek/XYColorIssue
As you can see:

All I do is init a Cell from XIB,
add the viewModel through `cellForRowAt`
and then in this method I need to clear the layers of the (in this example) cell.view.

Otherwise I end up with a bunch of subLayers.
And in my example it causes UI issues (not to mention the memory issues).

**Comment by davidseek** [comment]
If you in `class Cell: UITableViewCell {` comment out:

```
self.layer.sublayers?.forEach { layer in
   layer.removeFromSuperlayer()
}
```

.. it fixes the crashing issue.

**Comment by RayJiang16** [comment]
I think I know your issue. This crash has nothing to do with XYColor.

You **CAN NOT** remove all subLayer in UIView.


If you want to reset shapeLayer (or custom layer) you should do like that:
```
class Cell: UITableViewCell {
    
    var shapeLayer: CAShapeLayer?
    
    func bindViewModel(_ viewModel: Any) {
        shapeLayer?.removeFromSuperlayer()
        
        self.shapeLayer = CAShapeLayer()
        self.shapeLayer?.setBorderColor(.green, with: self)
        …
        self.layer.addSublayer(shapeLayer!)
    }
}
```

**Comment by davidseek** [comment]
That did the trick. 
Appreciate your time.
I guess I've never ran into such a niche case.
